/* icons.h - GENERATED by tools/gen_icons.py from the assets/icons PNGs.
 * Do not edit by hand; re-run the script after changing the art. */
#ifndef AQUA_PETS_ICONS_H
#define AQUA_PETS_ICONS_H
#include <stdint.h>

typedef struct { uint8_t w, h; const uint16_t *rgb; const uint8_t *a; } icon_t;

extern const icon_t icon_bold;
extern const icon_t icon_cautious;
extern const icon_t icon_curiosity;
extern const icon_t icon_curious;
extern const icon_t icon_energy;
extern const icon_t icon_hunger;
extern const icon_t icon_shy;
extern const icon_t icon_social;
extern const icon_t icon_solo;
extern const icon_t icon_stress;
extern const icon_t icon_trust;
extern const icon_t icon_unknown_16;
extern const icon_t icon_unknown_24;
extern const icon_t icon_ms_first_bubbles;
extern const icon_t icon_ms_first_dart;
extern const icon_t icon_ms_first_feeding;
extern const icon_t icon_ms_first_follow;
extern const icon_t icon_ms_first_glass_cleaning;
extern const icon_t icon_ms_first_hold_approach;
extern const icon_t icon_ms_first_meal;
extern const icon_t icon_ms_first_play_session;
extern const icon_t icon_ms_first_quiet_night;
extern const icon_t icon_ms_first_reef;
extern const icon_t icon_ms_first_seagrass;
extern const icon_t icon_ms_first_trimming;
extern const icon_t icon_ms_full_school;
extern const icon_t icon_ms_sand_dollar;
extern const icon_t icon_ms_tank_changed_someone;
extern const icon_t icon_shop_angler;
extern const icon_t icon_shop_castle;
extern const icon_t icon_shop_cluster;
extern const icon_t icon_shop_coral;
extern const icon_t icon_shop_crab;
extern const icon_t icon_shop_eel;
extern const icon_t icon_shop_lobster;
extern const icon_t icon_shop_octopus;
extern const icon_t icon_shop_plant;
extern const icon_t icon_shop_puffer;
extern const icon_t icon_shop_sand_dollar_16;
extern const icon_t icon_shop_sand_dollar_64;
extern const icon_t icon_shop_seahorse;
extern const icon_t icon_shop_shark;
extern const icon_t icon_shop_shrimp;
extern const icon_t icon_shop_snail;
extern const icon_t icon_shop_squid;
extern const icon_t icon_shop_swordfish;
extern const icon_t icon_shop_urchin;
extern const icon_t icon_snail_glass;
extern const icon_t icon_snail_upright;
extern const icon_t icon_tool_scissors;
extern const icon_t icon_tool_sponge;
/* per-theme shop thumbnails from their own generators (not assets/icons): */
extern const icon_t icon_shop_jellyfish;        /* common/jellyfish_assets.c, tools/gen_jellyfish_assets.py */
const icon_t *jellyfish_theme_icon(int theme);
extern const icon_t icon_shop_wreck;            /* the wreck (2026-10-10): common/wreck_assets.c, tools/gen_wreck_assets.py */
const icon_t *wreck_theme_icon(int theme);
extern const icon_t icon_shop_frogman;          /* the frogman (2026-10-10): common/frogman_assets.c, tools/gen_frogman_assets.py */
const icon_t *frogman_theme_icon(int theme);
extern const icon_t icon_shop_sub;              /* the submarine (2026-10-10 night): common/sub_assets.c, tools/gen_sub_assets.py */
const icon_t *sub_theme_icon(int theme);

#endif
