/* icons.h - GENERATED by tools/gen_icons.py from the assets/icons PNGs.
 * Do not edit by hand; re-run the script after changing the art. */
#ifndef POCKET_TANK_ICONS_H
#define POCKET_TANK_ICONS_H
#include <stdint.h>

typedef struct { uint8_t w, h; const uint16_t *rgb; const uint8_t *a; } icon_t;

extern const icon_t icon_bold;
extern const icon_t icon_cautious;
extern const icon_t icon_curiosity;
extern const icon_t icon_curious;
extern const icon_t icon_energy;
extern const icon_t icon_hunger;
extern const icon_t icon_shy;
extern const icon_t icon_social;
extern const icon_t icon_solo;
extern const icon_t icon_stress;
extern const icon_t icon_trust;
extern const icon_t icon_unknown_16;
extern const icon_t icon_unknown_24;
extern const icon_t icon_ms_first_bubbles;
extern const icon_t icon_ms_first_dart;
extern const icon_t icon_ms_first_feeding;
extern const icon_t icon_ms_first_follow;
extern const icon_t icon_ms_first_glass_cleaning;
extern const icon_t icon_ms_first_hold_approach;
extern const icon_t icon_ms_first_meal;
extern const icon_t icon_ms_first_play_session;
extern const icon_t icon_ms_first_quiet_night;
extern const icon_t icon_ms_first_reef;
extern const icon_t icon_ms_first_trimming;
extern const icon_t icon_ms_sand_dollar;
extern const icon_t icon_ms_tank_changed_someone;
extern const icon_t icon_shop_castle;
extern const icon_t icon_shop_cluster;
extern const icon_t icon_shop_coral;
extern const icon_t icon_shop_plant;
extern const icon_t icon_shop_sand_dollar_16;
extern const icon_t icon_shop_sand_dollar_64;
extern const icon_t icon_shop_snail;
extern const icon_t icon_snail_glass;
extern const icon_t icon_snail_upright;
extern const icon_t icon_ms_first_bubbles_24;
extern const icon_t icon_ms_first_dart_24;
extern const icon_t icon_ms_first_feeding_24;
extern const icon_t icon_ms_first_follow_24;
extern const icon_t icon_ms_first_glass_cleaning_24;
extern const icon_t icon_ms_first_hold_approach_24;
extern const icon_t icon_ms_first_meal_24;
extern const icon_t icon_ms_first_play_session_24;
extern const icon_t icon_ms_first_quiet_night_24;
extern const icon_t icon_ms_first_reef_24;
extern const icon_t icon_ms_first_trimming_24;
extern const icon_t icon_ms_sand_dollar_24;
extern const icon_t icon_ms_tank_changed_someone_24;

#endif
