#!/usr/bin/env python3
"""Bake the submarine's shop thumbnails (2026-10-10 night), one per theme, the frogman's way: a
little sub side-on, tower up, propeller behind, a few bubbles, in the theme's hull colours
(render.c draw_submarine); --check verifies the tracked outputs are what this script makes."""
from pathlib import Path
import sys,io
from gen_theme_assets import raster,array
root=Path(__file__).resolve().parent.parent
# hull, belly, trim, tower, glass, metal, mist - per theme
PAL=[('original',     '#f2c230','#d9a520','#3a3f44','#f2c230','#9fd8e2','#b8c0c6','#9fd8e2'),
     ('quiet-lagoon', '#5f8f62','#3f6a48','#c9a55a','#4e7a52','#c4e6d1','#b8c0c6','#c4e6d1'),
     ('tidepool-club','#e8524a','#fff4e0','#2fb8c8','#2fb8c8','#fff6d9','#ffc040','#3d8e83'),
     ('blackwater',   '#56606a','#23282d','#8a3a2a','#3e464e','#aee6f0','#b8c0c6','#c8e8ee')]
def svg(hull,belly,trim,tower,glass,metal,mist):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<circle cx="4" cy="12" r="1.1" fill="{mist}" opacity=".7"/><circle cx="2.5" cy="8" r="1.5" fill="{mist}" opacity=".5"/><circle cx="5.5" cy="5" r=".9" fill="{mist}" opacity=".5"/>
<rect x="3.5" y="17.6" width="4" height="1.6" fill="{metal}"/><ellipse cx="3.2" cy="18.4" rx="1" ry="4" fill="{metal}"/>
<path d="M8 15 L5 10 L6.5 10 L9.5 14 Z" fill="{trim}"/><path d="M8 22 L5 27 L6.5 27 L9.5 23 Z" fill="{trim}"/>
<ellipse cx="17" cy="18.4" rx="12.5" ry="5.6" fill="{hull}"/><ellipse cx="17" cy="20.6" rx="11.5" ry="2.8" fill="{belly}"/>
<ellipse cx="18" cy="15.2" rx="7.5" ry=".9" fill="#ffffff" opacity=".35"/>
<rect x="14" y="8.5" width="7" height="5" rx="1" fill="{tower}"/><rect x="14.5" y="7.6" width="6" height="1" fill="{trim}"/>
<rect x="17" y="3.6" width="1.4" height="5" fill="{metal}"/><rect x="17" y="3.4" width="3.6" height="1.4" fill="{metal}"/><circle cx="20.8" cy="4.1" r="1" fill="#20262a"/>
<circle cx="19" cy="11" r="1.1" fill="{glass}"/>
<circle cx="11" cy="18" r="1.5" fill="{trim}"/><circle cx="11" cy="18" r=".9" fill="{glass}"/>
<circle cx="17" cy="18" r="1.5" fill="{trim}"/><circle cx="17" cy="18" r=".9" fill="{glass}"/>
<circle cx="23" cy="18" r="1.5" fill="{trim}"/><circle cx="23" cy="18" r=".9" fill="{glass}"/>
<ellipse cx="27" cy="19.5" rx="3" ry=".9" fill="{trim}"/>
</svg>'''
outputs={};code=['/* Generated by tools/gen_sub_assets.py (2026-10-10). Do not edit. */\n#include "icons.h"\n']
for i,(name,*cols) in enumerate(PAL):
    base=root/'assets/themes'/name; s=svg(*cols)
    outputs[base/'shop_sub.svg']=(s+'\n').encode()
    im=raster(s.encode(),32,32);buf=io.BytesIO();im.save(buf,format='PNG');outputs[base/'shop_sub.png']=buf.getvalue()
    pixels=list(im.getdata());rgb=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b,a in pixels];alpha=[a for r,g,b,a in pixels]
    symbol='icon_shop_sub' if not i else f'sub_icon_{i}'
    code.extend([array(symbol+'_rgb','uint16_t',rgb),array(symbol+'_a','uint8_t',alpha),f'{"static " if i else ""}const icon_t {symbol}={{32,32,{symbol}_rgb,{symbol}_a}};\n'])
code.append('const icon_t *sub_theme_icon(int theme){return theme==1?&sub_icon_1:theme==2?&sub_icon_2:theme==3?&sub_icon_3:&icon_shop_sub;}\n')
outputs[root/'common/sub_assets.c']='\n'.join(code).encode()
for p,data in outputs.items():
    if '--check' in sys.argv: assert p.read_bytes()==data,f'Stale asset: {p}'
    else: p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(data)
print('Verified submarine icons' if '--check' in sys.argv else 'Generated 4 submarine SVG/PNG icons and common/sub_assets.c')
