#!/usr/bin/env python3
"""Bake the editable theme SVGs into PNGs and flash-resident RGB565 + alpha.

Requires Pillow and system librsvg-2/libcairo (no network at generation/runtime).
Run: python3 tools/gen_theme_assets.py [--check]
--check regenerates into memory and verifies every tracked output.
Existing Original icons remain untouched. UI replacements have identical extents.
"""
from pathlib import Path
import argparse
import ctypes as C
import ctypes.util
import hashlib
import io
import json
import re
import tempfile
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'common/theme_assets.c'
THEMES = [(1, 'quiet-lagoon'), (2, 'tidepool-club')]
PREVIEW_ONLY = [(3, 'blackwater')]   # a picker fish of its own; icons and fonts borrowed from the lagoon (theme_asset_set: flash)
class Rect(C.Structure):
    _fields_ = [('x', C.c_double), ('y', C.c_double), ('width', C.c_double), ('height', C.c_double)]

def raster(svg, w, h):
    """Supersample only at build time; firmware receives its native pixels."""
    rsvg = C.CDLL(ctypes.util.find_library('rsvg-2'))
    cairo = C.CDLL(ctypes.util.find_library('cairo'))
    gobj = C.CDLL(ctypes.util.find_library('gobject-2.0'))
    rsvg.rsvg_handle_new_from_data.argtypes = [C.c_char_p, C.c_size_t, C.c_void_p]
    rsvg.rsvg_handle_new_from_data.restype = C.c_void_p
    rsvg.rsvg_handle_render_document.argtypes = [C.c_void_p, C.c_void_p, C.POINTER(Rect), C.c_void_p]
    rsvg.rsvg_handle_render_document.restype = C.c_int
    cairo.cairo_image_surface_create.argtypes = [C.c_int, C.c_int, C.c_int]
    cairo.cairo_image_surface_create.restype = C.c_void_p
    cairo.cairo_create.argtypes = [C.c_void_p]; cairo.cairo_create.restype = C.c_void_p
    cairo.cairo_surface_write_to_png.argtypes = [C.c_void_p, C.c_char_p]
    cairo.cairo_destroy.argtypes = [C.c_void_p]; cairo.cairo_surface_destroy.argtypes = [C.c_void_p]
    gobj.g_object_unref.argtypes = [C.c_void_p]
    handle = rsvg.rsvg_handle_new_from_data(svg, len(svg), None)
    if not handle: raise ValueError('invalid SVG')
    surface = cairo.cairo_image_surface_create(0, w*4, h*4)
    cr = cairo.cairo_create(surface)
    try:
        if not rsvg.rsvg_handle_render_document(handle, cr, C.byref(Rect(0, 0, w*4, h*4)), None):
            raise ValueError('SVG rendering failed')
        with tempfile.TemporaryDirectory(prefix='aqua-art-') as tmp:
            png = Path(tmp) / 'render.png'
            if cairo.cairo_surface_write_to_png(surface, str(png).encode()): raise ValueError('PNG write failed')
            return Image.open(png).convert('RGBA').resize((w,h), Image.Resampling.LANCZOS)
    finally:
        cairo.cairo_destroy(cr); cairo.cairo_surface_destroy(surface); gobj.g_object_unref(handle)

def cname(stem):
    return 'icon_' + re.sub(r'[^a-z0-9]+','_',stem.replace('icon_','').lower()).strip('_')
def array(name, kind, data):
    vals = [f'0x{x:04x}' if kind=='uint16_t' else str(x) for x in data]
    return f'static const {kind} {name}[{len(data)}] = {{\n' + '\n'.join('    '+','.join(vals[i:i+20])+',' for i in range(0,len(vals),20)) + '\n};\n'

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    outputs={}; source=['/* GENERATED by tools/gen_theme_assets.py. Do not edit. */\n#include "theme.h"\n']
    replacements=[]; byte_count=0; manifest=[]
    original=sorted((ROOT/'assets/icons').glob('*.png'))
    for tid,directory in THEMES:
        base=ROOT/'assets/themes'/directory
        for src in original + [base/'fish.png']:
            preview=src==base/'fish.png'; w,h=(48,40) if preview else Image.open(src).size
            svg=base/(src.stem+'.svg'); img=raster(svg.read_bytes(),w,h)
            png=io.BytesIO(); img.save(png,format='PNG'); outputs[base/(src.stem+'.png')]=png.getvalue()
            name=f'theme_{tid}_{cname(src.stem)}'; rgb=[]; alpha=[]
            for r,g,b,a in img.getdata():
                rgb.append(((r>>3)<<11)|((g>>2)<<5)|(b>>3)); alpha.append(a)
            source += [array(name+'_rgb','uint16_t',rgb),array(name+'_a','uint8_t',alpha),f'static const icon_t {name} = {{{w},{h},{name}_rgb,{name}_a}};\n']
            if not preview: replacements.append((tid,cname(src.stem),name))
            byte_count+=w*h*3
            manifest.append({'theme':directory,'file':svg.name,'width':w,'height':h,'bytes':w*h*3,'sha256':hashlib.sha256(svg.read_bytes()).hexdigest()})
    for tid,directory in PREVIEW_ONLY:
        base=ROOT/'assets/themes'/directory; src=base/'fish.svg'; w,h=48,40
        img=raster(src.read_bytes(),w,h); png=io.BytesIO(); img.save(png,format='PNG'); outputs[base/'fish.png']=png.getvalue()
        name=f'theme_{tid}_icon_fish'; rgb=[]; alpha=[]
        for r,g,b,a in img.getdata():
            rgb.append(((r>>3)<<11)|((g>>2)<<5)|(b>>3)); alpha.append(a)
        source += [array(name+'_rgb','uint16_t',rgb),array(name+'_a','uint8_t',alpha),f'static const icon_t {name} = {{{w},{h},{name}_rgb,{name}_a}};\n']
        byte_count+=w*h*3
        manifest.append({'theme':directory,'file':src.name,'width':w,'height':h,'bytes':w*h*3,'sha256':hashlib.sha256(src.read_bytes()).hexdigest()})
    # A fixed cell and height preserve the existing software renderer's hit-test contract.
    for tid,directory in THEMES:
        font_path=ROOT/'assets/themes'/('DejaVuSansMono-Bold.ttf' if tid==2 else 'DejaVuSans.ttf')
        for scale in [2,3]:
            w,h=5*scale,7*scale; packed=[]
            font=ImageFont.truetype(str(font_path),h)
            cap_top=ImageDraw.Draw(Image.new('L',(w,h))).textbbox((0,0),'H',font=font)[1]   # one baseline for the cell (2026-10-10: each glyph sat on its own top, so a period floated to the cap line)
            for code in range(32,127):
                im=Image.new('L',(w,h)); d=ImageDraw.Draw(im); box=d.textbbox((0,0),chr(code),font=font)
                d.text(((w-(box[2]-box[0]))//2-box[0],-cap_top),chr(code),font=font,fill=255)
                pixels=list(im.getdata())
                for i in range(0,len(pixels),2): packed.append(((pixels[i]>>4)<<4)|((pixels[i+1]>>4) if i+1<len(pixels) else 0))
            source.append(array(f'font_{tid}_{scale}','uint8_t',packed)); byte_count+=len(packed)
    source.append('const icon_t *theme_asset_icon(int theme, const icon_t *original) {\n')
    for tid,_ in THEMES:
        source.append(f'    if (theme == {tid}) {{\n')
        source.extend(f'        if (original == &{old}) return &{new};\n' for theme_id,old,new in replacements if theme_id==tid)
        source.append('    }\n')
    source.append('    return original;\n}\n')
    previews=' : '.join(f'theme == {tid} ? &theme_{tid}_icon_fish' for tid,_ in THEMES+PREVIEW_ONLY)
    source.append(f'const icon_t *theme_preview_icon(int theme) {{\n    return {previews} : 0;\n}}\n')
    source.append('const uint8_t *theme_font_glyph(int theme, int scale, unsigned char ch) {\n    if (ch < 32 || ch > 126) return 0;\n')
    for tid,_ in THEMES:
        for scale in [2,3]: source.append(f'    if (theme == {tid} && scale == {scale}) return font_{tid}_{scale} + (ch - 32) * {(5*scale*7*scale+1)//2};\n')
    source.append('    return 0;\n}\n')
    outputs[OUT]='\n'.join(source).encode()
    outputs[ROOT/'assets/themes/manifest.json']=(json.dumps({'pixel_and_font_bytes':byte_count,'icons':manifest},indent=2)+'\n').encode()
    for path,data in outputs.items():
        if args.check:
            if not path.exists() or path.read_bytes()!=data: raise SystemExit(f'out of date: {path.relative_to(ROOT)}')
        else: path.write_bytes(data)
    print(f'{"Verified" if args.check else "Generated"} {len(manifest)} RGBA assets + 4 font atlases; {byte_count:,} bytes of flash pixel/font data. Original assets untouched.')
if __name__=='__main__': main()
