#!/usr/bin/env python3
"""Bake the frogman's shop thumbnails (2026-10-10), one per theme, the wreck's way: a diver
floating sideways, his suit in the theme's colours (render.c draw_frogman);
--check verifies the tracked outputs are what this script makes."""
from pathlib import Path
import sys,io
from gen_theme_assets import raster,array
root=Path(__file__).resolve().parent.parent
# suit, band, fin, tank, glass, mask, mist - per theme
PAL=[('original',    '#f5c242','#1d2a33','#d8402c','#b8c4cc','#9fd8e2','#1d2a33','#9fd8e2'),
     ('quiet-lagoon','#2fb8a6','#ff7f66','#8a5cc8','#e8d9a0','#c4e6d1','#264a44','#c4e6d1'),
     ('tidepool-club','#ff4f9a','#b6f05a','#33c7e0','#ff9f3f','#fff6d9','#5a2d7a','#3d8e83'),
     ('blackwater',   '#202428','#ffb020','#f2c230','#d4dade','#aee6f0','#0f1215','#c8e8ee')]
def svg(suit,band,fin,tank,glass,mask,mist):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<circle cx="24" cy="8" r="1.2" fill="{mist}" opacity=".8"/><circle cx="26.5" cy="4.5" r="1.6" fill="{mist}" opacity=".6"/><circle cx="22" cy="3" r=".9" fill="{mist}" opacity=".5"/>
<path d="M9 15 L3 12.5" stroke="{suit}" stroke-width="2.6" stroke-linecap="round"/><path d="M9 19 L3 21.5" stroke="{suit}" stroke-width="2.6" stroke-linecap="round"/>
<ellipse cx="2.6" cy="12" rx="2.6" ry="1.4" fill="{fin}" transform="rotate(-20 2.6 12)"/><ellipse cx="2.6" cy="22" rx="2.6" ry="1.4" fill="{fin}" transform="rotate(20 2.6 22)"/>
<rect x="8" y="10.2" width="14" height="4.4" rx="2.2" fill="{tank}"/><circle cx="22.5" cy="12.4" r="1.1" fill="#565a5d"/>
<ellipse cx="15" cy="17.5" rx="9" ry="4.3" fill="{suit}"/>
<rect x="10.2" y="13.6" width="2.4" height="7.8" rx="1" fill="{band}"/><rect x="17.4" y="13.6" width="2.4" height="7.8" rx="1" fill="{band}"/>
<path d="M18 19 L27 21" stroke="{suit}" stroke-width="2.4" stroke-linecap="round"/><circle cx="27.3" cy="21.2" r="1.6" fill="{band}"/>
<circle cx="25.5" cy="16" r="4.3" fill="{suit}"/><circle cx="27" cy="16.3" r="2.6" fill="#f1c69b"/>
<ellipse cx="27" cy="15" rx="2.9" ry="1.9" fill="{mask}"/><ellipse cx="27.3" cy="15" rx="2" ry="1.2" fill="{glass}"/>
</svg>'''
outputs={};code=['/* Generated by tools/gen_frogman_assets.py (2026-10-10). Do not edit. */\n#include "icons.h"\n']
for i,(name,*cols) in enumerate(PAL):
    base=root/'assets/themes'/name; s=svg(*cols)
    outputs[base/'shop_frogman.svg']=(s+'\n').encode()
    im=raster(s.encode(),32,32);buf=io.BytesIO();im.save(buf,format='PNG');outputs[base/'shop_frogman.png']=buf.getvalue()
    pixels=list(im.getdata());rgb=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b,a in pixels];alpha=[a for r,g,b,a in pixels]
    symbol='icon_shop_frogman' if not i else f'frogman_icon_{i}'
    code.extend([array(symbol+'_rgb','uint16_t',rgb),array(symbol+'_a','uint8_t',alpha),f'{"static " if i else ""}const icon_t {symbol}={{32,32,{symbol}_rgb,{symbol}_a}};\n'])
code.append('const icon_t *frogman_theme_icon(int theme){return theme==1?&frogman_icon_1:theme==2?&frogman_icon_2:theme==3?&frogman_icon_3:&icon_shop_frogman;}\n')
outputs[root/'common/frogman_assets.c']='\n'.join(code).encode()
for p,data in outputs.items():
    if '--check' in sys.argv: assert p.read_bytes()==data,f'Stale asset: {p}'
    else: p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(data)
print('Verified frogman icons' if '--check' in sys.argv else 'Generated 4 frogman SVG/PNG icons and common/frogman_assets.c')
