#!/usr/bin/env python3
"""Bake approved jellyfish shop thumbnails; --check verifies deterministic outputs."""
from pathlib import Path
import subprocess,sys,io,json
from gen_theme_assets import raster,array
root=Path(__file__).resolve().parent.parent
script=r'''
const fs=require('fs'),vm=require('vm');
const s=fs.readFileSync('docs/design/jellyfish/jellyfish.js','utf8');
const fn=vm.runInNewContext("let serial=0;const $=()=>({value:'open'});"+s.slice(s.indexOf('function jelly('),s.indexOf("$('designs').innerHTML"))+";jelly");
console.log(JSON.stringify([0,1,2].map(i=>'<svg xmlns="http://www.w3.org/2000/svg" viewBox="-60 -60 120 165">'+fn(i,0,'adult')+'</svg>')));
'''
svgs=json.loads(subprocess.check_output(['node','-e',script],cwd=root))
outputs={};code=['/* Generated by tools/gen_jellyfish_assets.py. */\n#include "icons.h"\n']
for i,svg in enumerate(svgs):
 name=['original','quiet-lagoon','tidepool-club'][i];base=root/'assets/themes'/name
 outputs[base/'shop_jellyfish.svg']=(svg+'\n').encode()
 im=raster(svg.encode(),32,32);buf=io.BytesIO();im.save(buf,format='PNG');outputs[base/'shop_jellyfish.png']=buf.getvalue()
 pixels=list(im.getdata());rgb=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b,a in pixels];alpha=[a for r,g,b,a in pixels]
 symbol='icon_shop_jellyfish' if not i else f'jellyfish_icon_{i}'
 code.extend([array(symbol+'_rgb','uint16_t',rgb),array(symbol+'_a','uint8_t',alpha),f'{"static " if i else ""}const icon_t {symbol}={{32,32,{symbol}_rgb,{symbol}_a}};\n'])
code.append('const icon_t *jellyfish_theme_icon(int theme){return theme==1||theme==3?&jellyfish_icon_1:theme==2?&jellyfish_icon_2:&icon_shop_jellyfish;}\n')   # Blackwater (2026-10-10) shows the lagoon's moon jelly
outputs[root/'common/jellyfish_assets.c']='\n'.join(code).encode()
for p,data in outputs.items():
 if '--check' in sys.argv:
  assert p.read_bytes()==data,f'Stale asset: {p}'
 else:p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(data)
print('Verified jellyfish icons' if '--check' in sys.argv else 'Generated 3 jellyfish SVG/PNG icons and 9,216 bytes of native pixels')
