#!/usr/bin/env python3
"""gen_icons.py - bake assets/icons/*.png into common/icons.c + icons.h.

Full-color pixel-art icons, hand-drawn (the style: 16/24 px, hard edges,
three-tone shading). Each PNG becomes an icon_t: RGB565
pixels + an 8-bit alpha plane, blended at draw time by render.c's
blit_icon() (which can also scale alpha for dimming/unrevealed states).

The milestone badges (ms_*.png, 32 px) also get a 24 px copy, icon_ms_*_24:
a short tank (the 2.8" CYD, 240 px tall) cannot fit its rows of 32 px
badges, and pixel art drawn at 32 px has no clean half size. Box-filtered,
the art survives the step down; a tall tank never references the copies and
the linker drops them.

Run from anywhere; paths are repo-relative to this file:
    ~/.venvs/pocket-tank/bin/python tools/gen_icons.py
"""
import os, re, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "icons")
SMALL_PREFIX, SMALL_SIZE = "ms_", 24          # which art gets a small copy, and its size
OUT_C = os.path.join(ROOT, "common", "icons.c")
OUT_H = os.path.join(ROOT, "common", "icons.h")


def cname(fn):
    stem = os.path.splitext(fn)[0]
    return "icon_" + re.sub(r"[^a-z0-9]+", "_", stem.replace("icon_", "").lower()).strip("_")


def main():
    files = sorted(f for f in os.listdir(SRC) if f.endswith(".png"))
    if not files:
        sys.exit(f"no PNGs in {SRC}")
    decls, defs, table = [], [], []
    total = 0
    def emit(img, n):
        nonlocal total
        w, h = img.size
        px = list(img.getdata())
        rgb, alp = [], []
        for r, g, b, a in px:
            rgb.append(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))
            alp.append(a)
        total += w * h * 3
        defs.append(f"static const uint16_t {n}_rgb[{w * h}] = {{\n"
                    + wrap(", ".join(f"0x{v:04x}" for v in rgb)) + "\n};")
        defs.append(f"static const uint8_t {n}_a[{w * h}] = {{\n"
                    + wrap(", ".join(str(v) for v in alp)) + "\n};")
        table.append(f"const icon_t {n} = {{ {w}, {h}, {n}_rgb, {n}_a }};")
        decls.append(f"extern const icon_t {n};")

    for fn in files:
        img = Image.open(os.path.join(SRC, fn)).convert("RGBA")
        w, h = img.size
        if w > 64 or h > 64:
            sys.exit(f"{fn}: {w}x{h} is too big for a UI icon (max 64)")
        emit(img, cname(fn))
    # the small copies after every full-size icon, so the file above them is
    # byte-for-byte what it was before they existed
    for fn in files:
        if fn.startswith(SMALL_PREFIX):
            img = Image.open(os.path.join(SRC, fn)).convert("RGBA")
            # Pillow resizes RGBA through premultiplied alpha, so the
            # transparent edge does not bleed dark into the art
            emit(img.resize((SMALL_SIZE, SMALL_SIZE), Image.BOX), f"{cname(fn)}_{SMALL_SIZE}")
    hdr = (
        "/* icons.h - GENERATED by tools/gen_icons.py from the assets/icons PNGs.\n"
        " * Do not edit by hand; re-run the script after changing the art. */\n"
        "#ifndef POCKET_TANK_ICONS_H\n#define POCKET_TANK_ICONS_H\n"
        "#include <stdint.h>\n\n"
        "typedef struct { uint8_t w, h; const uint16_t *rgb; const uint8_t *a; } icon_t;\n\n"
        + "\n".join(decls) + "\n\n#endif\n")
    src = (
        "/* icons.c - GENERATED by tools/gen_icons.py from the assets/icons PNGs. */\n"
        '#include "icons.h"\n\n' + "\n\n".join(defs) + "\n\n" + "\n".join(table) + "\n")
    open(OUT_H, "w").write(hdr)
    open(OUT_C, "w").write(src)
    print(f"wrote {len(table)} icons, {total / 1024:.1f} KB of pixel data")
    for f in files:
        print(f"  {cname(f)}")


def wrap(s, width=100):
    out, line = [], "    "
    for tok in s.split(", "):
        if len(line) + len(tok) + 2 > width:
            out.append(line.rstrip())
            line = "    "
        line += tok + ", "
    out.append(line.rstrip().rstrip(","))
    return "\n".join(out)


if __name__ == "__main__":
    main()
